cabal-extras

diff --git a/x-unix/cabal b/x-unix/cabal
--- a/x-unix/cabal
+++ b/x-unix/cabal
@@ -17,13 +17,14 @@ Commands:
     lint            Lint the project.
     init            Start a new project.
     update          Cabal update, but limited to retrieving at most once per day.
+    clean           Remove compiled artifacts.
 EOF
     exit ${status}
 }
 
 fail () {
      message="${1:-}"
-     [ -z "$message" ] || echo message 1>&2
+     [ -z "$message" ] || echo "${message}" 1>&2
      usage 1 1>&2
 }
 
@@ -41,16 +42,19 @@ project_name () {
 # brute force wins.
 #
 initialize () {
-    # sandbox initialized if required, this should support sandboxes in parent directories
-    [ -f cabal.sandbox.config ] || {
-        cabal sandbox init
-    }
-
     # sandbox has all sources
     project=$(project_name)
+    SANDBOX_DIR=.cabal-sandbox
     [ ! -f "${project}.sandbox" ] || {
-        SANDBOX="--sandbox $(cat ${project}.sandbox)"
+        SANDBOX_DIR=$(cat ${project}.sandbox)
+        SANDBOX="--sandbox ${SANDBOX_DIR}"
     }
+
+    # sandbox initialized if required, this should support sandboxes in parent directories
+    [ -f cabal.sandbox.config ] || {
+        cabal sandbox ${SANDBOX:-} init
+    }
+
     [ ! -f "$project.submodules" ] || {
         # submodules initialized if required, the "has it been done before" is pretty crude, but check is useful.
         cat $project.submodules | while read submodule; do
@@ -62,8 +66,9 @@ initialize () {
         )
 
         cat $project.submodules | while read submodule; do
-            # ideally this would be conditional but yeh, stuff
-            cabal sandbox add-source ${SANDBOX:-} "$submodule"
+            if ! grep -q "${submodule}\"" ${SANDBOX_DIR}/add-source-timestamps; then
+                cabal sandbox add-source ${SANDBOX:-} "$submodule"
+            fi
         done
     }
 
@@ -77,7 +82,7 @@ initialize () {
 #
 run_build () {
     initialize
-    cabal build
+    cabal build --ghc-option="-Werror"
 }
 
 #
@@ -101,7 +106,19 @@ run_repl () {
 #
 run_quick () {
     initialize
-    ghci -package-db=$(find .cabal-sandbox -name '*-packages.conf.d') -isrc -itest test/test.hs
+    [ $# -eq 1 ] || fail "Quick requires a single argument, specifying the entry point you want to load."
+    [ -f "$1" ] || fail "The entry point does not exist."
+    [ ! -d src ] || SRC_DIRS="-isrc"
+    [ ! -d test ] || SRC_DIRS="${SRC_DIRS:-} -itest"
+    [ ! -d dist/build/autogen ] || SRC_DIRS="${SRC_DIRS:-} -idist/build/autogen"
+    ghci -package-db=$(find .cabal-sandbox -name '*-packages.conf.d') ${SRC_DIRS:-} "$1"
+}
+
+#
+# Remove compiled artifacts.
+#
+run_clean () {
+    cabal clean
 }
 
 #
@@ -171,6 +188,6 @@ esac
 
 MODE="$1"; shift
 case "$MODE" in
-build|test|repl|quick|demo|exec|tags|lint|init|update) run_$MODE "$@" ;;
+build|test|repl|quick|demo|exec|tags|lint|init|update|clean) run_$MODE "$@" ;;
 *) fail "Unknown mode: $MODE"
 esac
